name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
        contents: write 
        pages: write
        id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Codon
        run: |
          /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)" || true
          echo "$HOME/.codon/bin" >> "$GITHUB_PATH"

      - name: Check Codon
        run: |
          which codon
          codon --version

      - name: Install oj-verify
        run: |
          pip install "setuptools<81"
          pip install online-judge-verify-helper
      
      - name: Patch online-judge-verify-helper
        run: |
          python - <<'PY'
          import onlinejudge_verify.languages.list as x

          path = x.__file__
          print("Patching:", path)

          with open(path, encoding="utf-8") as f:
              s = f.read()

          # ここにローカルで行った変更を書く
          s = s.replace(
              "_dict['.py'] = PythonLanguage()",
              ""
          )

          with open(path, "w", encoding="utf-8") as f:
              f.write(s)
          PY
          


      - name: Verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          oj-verify --config-file .verify-helper/docs-config.toml all
      - name: Check files
        run: |
          pwd
          ls -la
          find . -name bundle.py

      - name: Generate documentation
        run: |
          oj-verify --config-file .verify-helper/docs-config.toml docs 

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: false

      - name: Build Jekyll site
        working-directory: .verify-helper/markdown 
        run: |
          bundle install --path .vendor/bundle
          bundle exec jekyll build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .verify-helper/markdown/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4